export const products = [
    {
        id:1,
        categoryId: 1,
        title:"Placa de video INNO3D Nvidia Geforce RTX 3080 10GB DDR6X LHR ",
        stock: 3,
        price: 240000,
        priceList:264000,
        thumbnail: "https://res.cloudinary.com/dbhovombt/image/upload/v1670437791/1655924848_sfgre_eslj2d.png",
        description: "La tarjeta gráfica GeForce RTX 3080 ofrecen el alto rendimiento que buscan los gamers. Basado en Ampere, la segunda generación de la arquitectura RTX de NVIDIA, cuentan con Núcleos RT mejorados y Núcleos Tensor, nuevos multiprocesadores de transmisión y memorias GDDR6X súper rápidas, para una experiencia de juego simplemente increíble.",
    },
    {
        id:2,
        categoryId: 1,
        title:"Motherboard Gigabyte Z690 AORUS ELITE DDR4 S1700",
        stock: 6,
        price: 75000,
        priceList:82500,
        thumbnail: "https://res.cloudinary.com/dbhovombt/image/upload/v1670438252/1659008113_z690_aorus_elite_ddr4-01_mjthqy.png",
        description: "La motherboard Gigabyte Z690 viene con una mejorada solucion para la energia, los ultimos estandares de almacenamiento y una gran conectividad para optimizar la performance en el gaming.",
    },
    {
        id:3,
        categoryId: 1,
        title:"Microprocesador AMD Ryzen 7 5700X 8/16 4.6gHz",
        stock: 12,
        price: 71000,
        priceList:78100,
        thumbnail: "https://res.cloudinary.com/dbhovombt/image/upload/v1670438884/ryzen7png_fywq96.png",
        description: "Los procesadores para computadoras de escritorio AMD Ryzen™ serie 5000 permiten disfrutar los juegos más exigentes y arrasan en tareas de varios subprocesos, como el renderizado de video o 3D, y la compilación de software. Con los procesadores Ryzen que incluye esta promoción, obtendrás hasta 16 núcleos, 32 subprocesos, velocidades turbo máximas de 4,9 GHz1 y caché de hasta 100 MB. Los procesadores AMD Ryzen™ serie 5000 ofrecen un rendimiento revolucionario.",
    },
    {
        id:4,
        categoryId: 2,
        title:"Mouse inalambrico Logitech G PRO X SUPERLIGHT WHITE",
        stock: 20,
        price: 22000,
        priceList:24200,
        thumbnail: "https://res.cloudinary.com/dbhovombt/image/upload/v1670439320/gproxsuperlightpng_fuk1ny.png",
        description: "Elimina todos los obstáculos para ganar con nuestro mouse inalámbrico PRO más ligero y rápido. El nuevo favorito de los mejores profesionales de esports pesa menos de 63 gramos y se desliza sin apenas fricción. PRO X SUPERLIGHT hace gala de nuestra tecnología de diseño ZERØ OPOSICIÓN, nuestro propósito de eliminar obstáculos y crear una conexión lo más pura posible entre el jugador y el juego.",
    },
    {
        id:5,
        categoryId: 2,
        title:"Teclado Mecanico Gamer Razer Huntsman Mini 60% Chroma",
        stock: 2,
        price: 30000,
        priceList:33000,
        thumbnail: "https://res.cloudinary.com/dbhovombt/image/upload/v1670439578/razerhuntsmanminipng_qxmzt9.png",
        description: "Entra en una nueva dimensión letal con el Razer Huntsman Mini: un teclado para juegos reducido al 60 % de su tamaño y con sus punteros switches ópticos Razer™. Portátil e ideal para escritorios reducidos, es hora de experimentar un accionamiento a la velocidad de la luz con nuestro diseño más compacto hasta la fecha.",
    },
    {
        id:6,
        categoryId: 2,
        title:"Auricular inalambrico HyperX Cloud Flight",
        stock: 8,
        price: 24000,
        priceList:26400,
        thumbnail: "https://res.cloudinary.com/dbhovombt/image/upload/v1670439723/cloudflightpng_ivjxjc.png",
        description: "Escapa de los limites de las conexiones por cable y muevete libremente con los HyperX Cloud Flight™ inalambricos. Con una conexión inalámbrica sólida para juegos, una increíble duración de la batería de 30 horas y la comodidad exclusiva de HyperX, Cloud Flight te permite jugar sin interrupciones durante más tiempo.",
    },
    {
        id:7,
        categoryId: 3,
        title:"Notebook Asus X515EA-EJ711 i3 1115G4 8GB SSD 256GB 15.6'",
        stock: 11,
        price: 145000,
        priceList:159500,
        thumbnail: "https://res.cloudinary.com/dbhovombt/image/upload/v1670440111/notebookasus_x515_png_vkcwsd.png",
        description: "Ya sea para trabajar o jugar, el ASUS X515 es el computador portátil que ofrece un potente rendimiento y efectos visuales envolventes. Su pantalla NanoEdge cuenta con amplios ángulos de visión de 178° y un recubrimiento antirreflejos mate para tener una experiencia verdaderamente atractiva.",
    },
    {
        id:8,
        categoryId: 3,
        title:"Notebook BANGHO GAME MASTER 15Z11 I5 11400H 16GB SSD 1TB GTX1650 15.6 W11",
        stock: 15,
        price: 280000,
        priceList:308000,
        thumbnail: "https://res.cloudinary.com/dbhovombt/image/upload/v1670440259/notebook_bangho_master_png_jzmyap.png",
        description: "Notebook Banghó Game Master GM-15Z11 GTX 1650, fue creada para aportar mayor velocidad en el juego y portabilidad. Equipada con Procesador Intel Core i5 de 11ava generación de serie H, placa gráfica NVIDIA Geforce GTX 1650 de 4GB GDDR6 y pantalla Full HD 15,6",
    },
    {
        id:9,
        categoryId: 3,
        title:"Notebook ASUS ZENBOOK UM425QA-KI164W RYZEN 5 5600H 8GB SSD 512GB 14 W11",
        stock: 7,
        price: 275000,
        priceList:302500,
        thumbnail: "https://res.cloudinary.com/dbhovombt/image/upload/v1670440475/notebook_asus_zenbookpng_nw5ahf.png",
        description: "El increíblemente compacto, fino y ligero ZenBook 14 cuenta con un procesador AMD Ryzen™ 4000 Series Mobile Processors que ofrece un rendimiento completo e incluye puertos HDMI, USB-C® y USB Tipo A, y un lector de tarjetas microSD para una versatilidad incomparable.",
    },
    {
        id:10,
        categoryId: 1,
        title:"Memoria RAM 16GB DDR5 5200MHZ KINGSTON FURY BEAST NEGRA",
        stock: 9,
        price: 45000,
        priceList:49500,
        thumbnail: "https://res.cloudinary.com/dbhovombt/image/upload/v1670440686/kingston_fury_16gbpng_azzx8x.png",
        description: "La memoria Kingston FURY™ Beast DDR5 ofrece la última tecnología de vanguardia para las plataformas de juegos de última generación. Llevando la velocidad, la capacidad y la confiabilidad aún más allá, DDR5 llega con un arsenal de funciones mejoradas, como ECC integrado (ODECC) para mejorar la estabilidad a velocidades extremas, subcanales duales de 32 bits para aumentar la eficiencia y un circuito integrado de administración de energía en el módulo. (PMIC) para proporcionar jugo donde más se necesita.",
    },
];

